config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users

  resources :recipes do
    member do
      post :parse
    end
    resources :comments, only: [:create], module: nil
  end

  resources :steps do
    resources :comments, only: [:create], controller: "comments"
  end

  resources :ingredients
end

app/views/ingredient_templates/index.html.erb
<h1>
  List of all ingredients
</h1>

<hr>

<article>
  <header>
    <h2>
      Add a new ingredient
    </h2>
  </header>

  <%= form_with url: ingredients_path, scope: :ingredient do |f| %>
    <div>
      <%= f.label :recipe_id, "Recipe" %>
      <%= f.number_field :recipe_id %>
    </div>

    <div>
      <%= f.label :unit, "Unit" %>
      <%= f.text_field :unit %>
    </div>

    <div>
      <%= f.label :amount, "Amount" %>
      <%= f.text_field :amount %>
    </div>

    <div>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
    </div>

    <%= f.submit "Create ingredient" %>
  <% end %>
</article>

<hr>

<article>
  <ul>
    <% @list_of_ingredients.each do |an_ingredient| %>
      <li>
        <%= link_to "Ingredient ##{an_ingredient.id}", ingredient_path(an_ingredient) %>
      </li>
    <% end %>
  </ul>
</article>

<hr>

app/views/ingredient_templates/show.html.erb
<h1>
  Ingredient #<%= @the_ingredient.id %> details
</h1>

<article>
  <div>
    <%= link_to "Go back", ingredients_path %>
  </div>

  <div>
    <%= button_to "Delete ingredient", ingredient_path(@the_ingredient), method: :delete, data: { turbo_confirm: "Delete this ingredient?" } %>
  </div>
  <dl>
    <dt>
      Recipe
    </dt>
    <dd>
      <%= @the_ingredient.recipe_id %>
    </dd>

    <dt>
      Unit
    </dt>
    <dd>
      <%= @the_ingredient.unit %>
    </dd>

    <dt>
      Amount
    </dt>
    <dd>
      <%= @the_ingredient.amount %>
    </dd>

    <dt>
      Name
    </dt>
    <dd>
      <%= @the_ingredient.name %>
    </dd>

    <dt>
      Created at
    </dt>
    <dd>
      <%= time_ago_in_words(@the_ingredient.created_at) %> ago
    </dd>

    <dt>
      Updated at
    </dt>
    <dd>
      <%= time_ago_in_words(@the_ingredient.updated_at) %> ago
    </dd>
  </dl>
</article>

<hr>


<article>
  <header>
    <h2>
      Edit ingredient
    </h2>
  </header>

  <%= form_with model: @the_ingredient, url: ingredient_path(@the_ingredient), method: :patch do |f| %>
    <div class="mb-3">
      <%= f.label :recipe_id, "Recipe", class: "form-label" %>
      <%= f.number_field :recipe_id, class: "form-control", required: true %>
    </div>

    <div class="mb-3">
      <%= f.label :unit, "Unit", class: "form-label" %>
      <%= f.text_field :unit, class: "form-control", required: true, maxlength: 255 %>
    </div>

    <div class="mb-3">
      <%= f.label :amount, "Amount", class: "form-label" %>
      <%= f.text_field :amount, class: "form-control", required: true, maxlength: 255 %>
    </div>

    <div class="mb-3">
      <%= f.label :name, "Name", class: "form-label" %>
      <%= f.text_field :name, class: "form-control", required: true, maxlength: 255 %>
    </div>

    <%= f.submit "Update ingredient", class: "btn btn-primary" %>
  <% end %>
</article>

<hr>