config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users

  resources :recipes do
    member do
      post :parse
    end
    resources :comments, only: [:create], module: nil
  end

  resources :steps do
    resources :comments, only: [:create], controller: "comments"
  end

  resources :ingredients
end

app/views/step_templates/index.html.erb
<h1>
  List of All Steps
</h1>

<hr>

<article>
  <header>
    <h2>
      Add a New Step
    </h2>
  </header>

  <%= form_with url: steps_path, scope: :step do |f| %>
    <div>
      <%= f.label :recipe_id, "Recipe" %>
      <%= f.number_field :recipe_id %>
    </div>

    <div>
      <%= f.label :position, "Position" %>
      <%= f.text_field :position %>
    </div>

    <div>
      <%= f.label :instruction, "Instruction" %>
      <%= f.text_field :instruction %>
    </div>

    <%= f.submit "Create step" %>
  <% end %>
</article>

<hr>

<article>
  <ul>
    <% @list_of_steps.each do |a_step| %>
      <li>
        <%= link_to "Step ##{a_step.id}", step_path(a_step) %>
      </li>
    <% end %>
  </ul>
</article>

<hr>

app/views/step_templates/show.html.erb
<h1>
  Step #<%= @the_step.id %> details
</h1>

<article>
  <div>
    <%= link_to "Go back", steps_path %>
  </div>

  <div>
    <%= button_to "Delete step", step_path(@the_step), method: :delete, data: { turbo_confirm: "Delete this step?" } %>
  </div>
  <dl>
    <dt>
      Recipe
    </dt>
    <dd>
      <%= @the_step.recipe_id %>
    </dd>

    <dt>
      Position
    </dt>
    <dd>
      <%= @the_step.position %>
    </dd>

    <dt>
      Instruction
    </dt>
    <dd>
      <%= @the_step.instruction %>
    </dd>

    <dt>
      Created at
    </dt>
    <dd>
      <%= time_ago_in_words(@the_step.created_at) %> ago
    </dd>

    <dt>
      Updated at
    </dt>
    <dd>
      <%= time_ago_in_words(@the_step.updated_at) %> ago
    </dd>
  </dl>
</article>

<hr>


<article>
  <header>
    <h2>
      Edit step
    </h2>
  </header>

  <%= form_with model: @the_step, url: step_path(@the_step), method: :patch do |f| %>
    <div class="mb-3">
      <%= f.label :recipe_id, "Recipe", class: "form-label" %>
      <%= f.number_field :recipe_id, class: "form-control", required: true %>
    </div>

    <div class="mb-3">
      <%= f.label :position, "Position", class: "form-label" %>
      <%= f.text_field :position, class: "form-control", required: true %>
    </div>

    <div class="mb-3">
      <%= f.label :instruction, "Instruction", class: "form-label" %>
      <%= f.text_field :instruction, class: "form-control", required: true, maxlength: 2000 %>
    </div>

    <%= f.submit "Update step", class: "btn btn-primary" %>
  <% end %>
</article>

<hr>